# Site settings
title: Bud 'n' Burger
description:
baseurl: ""
url: ""
social:
  twitter:
  facebook:
  instagram:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/_sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE
